version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.1.0
    command: ganache-cli -h 0.0.0.0
    ports:
      - "8545:8545"
  learntoken_test:
    image: learntoken:dev
    environment:
    - DEVELOPMENT_HOST=ganache
    command: bash -c "truffle test --network development && ./node_modules/.bin/solidity-coverage"
    depends_on:
    - ganache
    volumes:
    - ./reports:/code/reports